version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    platform: linux/amd64
    image: postgres:16
    container_name: fake-google-db-dev
    environment:
      POSTGRES_DB: fakegoogle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/pgdata
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${DEV_DB_PORT:-5434}:5432" # Default to 5434 for dev to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fakegoogle"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fake-google-network-dev

  # Next.js Application (Development)
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: fake-google-app-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:admin@postgres:5432/fakegoogle
      GOOGLE_SEARCH_API_KEY: ${GOOGLE_SEARCH_API_KEY:-}
      GOOGLE_SEARCH_ENGINE_ID: ${GOOGLE_SEARCH_ENGINE_ID:-}
      GOOGLE_GEMINI_API_KEY: ${GOOGLE_GEMINI_API_KEY:-}
      PORT: 3000
    ports:
      - "${DEV_APP_PORT:-3002}:3000" # Default to 3002 for dev to avoid conflicts
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev
    networks:
      - fake-google-network-dev

volumes:
  postgres_data_dev:
    driver: local

networks:
  fake-google-network-dev:
    driver: bridge
